dist: bionic

language: php

php:
  - 7.4.2
services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
    - DATABASE_URI="mysql://root:unittest@localhost/blog"

before_script:
  - sudo mysql -u root < database/structure.sql
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
